#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
repo_dir="$(CDPATH= cd -- "$script_dir/.." && pwd)"
config_file="$repo_dir/config/config.env"
secrets_file="$repo_dir/config/secrets.env"

run_existing() {
  local description="$1"
  shift
  if confirm "$description"; then
    if ! "$@"; then
      warn "The existing command failed. Stopping here; fix the reported error before re-running the wizard."
      return 1
    fi
  else
    warn "Skipped. Re-run this wizard when you are ready."
  fi
}

banner "OnyxClaw CCE + AgentSphere manual setup"

stage "Choose the infrastructure and APP access paths"
say "This wizard guides only human console actions and writes the existing local config files."
step "Choose exactly one infrastructure path: existing/manual cloud resources, or Terraform managed infrastructure."
step "For Terraform, it may create VPC/CCE/NAT/SNAT/SFS only after you review a concrete plan; this wizard never runs terraform apply."
step "Choose the APP browser entry before first deployment: node EIP + NodePort, or public-elb. Public ELB creates new public exposure."
if ! confirm "Is this a first deployment, or does an approved migration plan already cover the APP Service access-mode change?"; then
  warn "Stopped before making local changes. Existing APP Services must not switch access mode in place."
  exit 0
fi
if ! confirm "Run the existing scripts/init.sh now to create missing local config files with mode 600?"; then
  warn "Stopped before making local changes. The wizard requires the existing config initialization path."
  exit 0
fi
"$repo_dir/scripts/init.sh"
if confirm "Use public-elb for the APP browser entry?"; then
  APP_ACCESS_MODE=public-elb
else
  APP_ACCESS_MODE=nodeport
fi
note "Use the official prerequisite guide for either path. Do not pre-create the Channel ELB or its 18890/TCP listener."
open_url "https://support.huaweicloud.com/usermanual-cce/cce_10_0107.html"
pause "After choosing the path and confirming your cn-south-1 account permissions, press Enter."

stage "Create or verify VPC, CCE, and kubeconfig"
say "CCE, AgentSphere Gateway/Template, Sandbox, and SFS Turbo must use the same VPC."
open_url "https://support.huaweicloud.com/intl/zh-cn/usermanual-cce/cce_10_0028.html"
step "Create or verify the CCE cluster and at least one Ready worker node. Ensure VPC, Pod CIDR, and Service CIDR do not overlap."
step "Enable API Server public access if this deployment machine is external, then download the public kubeconfig anew."
open_url "https://support.huaweicloud.com/usermanual-cce/cce_10_0107.html"
ask KUBECONFIG "Paste the absolute local kubeconfig path (not its contents):"
ENV_FILE="$config_file"
write_env KUBECONFIG "$KUBECONFIG"
note "The kubeconfig itself is never read by this wizard and must stay outside this repository with mode 600."

stage "Configure Sandbox egress and SFS Turbo"
open_url "https://support.huaweicloud.com/usermanual-natgateway/zh-cn_topic_0127489529.html"
step "Create or verify a NAT Gateway and SNAT rule for the actual Sandbox subnet, with DNS and HTTPS 443 egress to the model endpoint."
step "Do not substitute a node or APP EIP for the Sandbox SNAT EIP."
open_url "https://support.huaweicloud.com/usermanual-sfsturbo/sfsturbo_01_0359.html"
step "Create or verify an NFS SFS Turbo filesystem in the same VPC/AZ and copy its filesystem ID and console NFS shared root."
ask SFS_TURBO_ID "Paste the SFS Turbo filesystem ID:"
ask SFS_NFS_ENDPOINT "Paste the SFS console NFS shared root (for later workspace preparation):"
ENV_FILE="$config_file"
write_env SFS_TURBO_ID "$SFS_TURBO_ID"

stage "Create or verify the AgentSphere private gateway"
open_url "https://support.huaweicloud.com/usermanual-agentsphere/agentsphere_03_0024.html"
step "Create or select an available AgentSphere gateway in the same VPC/subnet and enable private-network access."
step "Copy its private Sandbox data-plane URL, not a public or control-plane URL."
ask AGENTSPHERE_SANDBOX_URL "Paste the private Sandbox data-plane URL:"
ENV_FILE="$config_file"
write_env AGENTSPHERE_SANDBOX_URL "$AGENTSPHERE_SANDBOX_URL"

stage "Create the AgentSphere OpenClaw Template"
open_url "https://support.huaweicloud.com/usermanual-agentsphere/agentsphere_03_0006.html"
step "Create a Template using the same VPC/subnet and the private gateway."
step "For the image, paste: swr.cn-south-1.myhuaweicloud.com/demo-test/onyxclaw-openclaw:0.3.9-channel-error-fix-v21"
step "Set HTTP health check path /health on port 49983, use an idle timeout appropriate for the account, and do not statically mount SFS here."
step "After the Template becomes available, copy its Template ID."
ask AGENTSPHERE_TEMPLATE_ID "Paste the AgentSphere Template ID:"
ENV_FILE="$config_file"
write_env AGENTSPHERE_TEMPLATE_ID "$AGENTSPHERE_TEMPLATE_ID"

stage "Complete the local deployment configuration"
ENV_FILE="$config_file"
write_env APP_ACCESS_MODE "$APP_ACCESS_MODE"
ask APP_IMAGE "Paste the immutable APP image reference (image@sha256:...):"
write_env APP_IMAGE "$APP_IMAGE"
note "Only KUBECONFIG, gateway URL, Template ID, SFS ID, APP_IMAGE, and the chosen access mode are written to config/config.env."

stage "Enter the two API keys safely"
say "Paste values only from your own secure source. Input is hidden and the wizard never prints the values."
ENV_FILE="$secrets_file"
ask_secret AGENTSPHERE_E2B_API_KEY "Paste the AgentSphere E2B API key:"
write_env AGENTSPHERE_E2B_API_KEY "$AGENTSPHERE_E2B_API_KEY"
ask_secret MODEL_API_KEY "Paste the model provider API key:"
write_env MODEL_API_KEY "$MODEL_API_KEY"
chmod 600 "$secrets_file"
note "No GitHub secrets are created: this package has no CI secret references for this deployment path."

stage "Prepare SFS and run safe validation gates"
say "The following existing commands remain the only implementation paths. Formal deployment is intentionally not run here."
run_existing "Initialize /onyxclaw/workspace on the selected SFS using the existing prepare-sfs.sh?" \
  "$repo_dir/scripts/prepare-sfs.sh" --kubeconfig "$KUBECONFIG" --nfs-endpoint "$SFS_NFS_ENDPOINT" --share-path /onyxclaw/workspace
run_existing "Run the offline deployment input validation?" \
  node "$repo_dir/scripts/deploy.mjs" --config "$config_file" --secrets "$secrets_file" --dry-run
run_existing "Run the CCE read-only cluster and ownership check?" "$repo_dir/scripts/deploy.sh" --check-cluster
run_existing "Run the API-server dry-run? A missing namespace may be created, but no other object is persisted." \
  "$repo_dir/scripts/deploy.sh" --server-dry-run
say "To deploy after reviewing these results, run: ./scripts/deploy.sh"
say "Then complete browser acceptance: create Sandbox, confirm SOUL.md, Channel callback, one model reply, pause/resume, and reset/kill the explicit Sandbox ID."

finish
